### ISSUE TITLE
Pagination is not working properly

### ISSUE THREAD

**Issue by alefaut** [fayak/zarakfr#28]
There is a link on home page to go to the second page : https://zarak.fr/page/2/
On the second page, there is a link to the first page : https://zarak.fr/page/:num/ which result in 404 error
If I go the the page list : https://zarak.fr/page/ there is no page 1.

Guess that's documented here : https://jekyllrb.com/docs/pagination/
part "Beware the page one edge-case"

**Comment by fayak** [comment]
Thanks ! Fixed and deployed
